disabled_rules: # rule identifiers to exclude from running
 - trailing_whitespace
 - force_cast
 - line_length
 - identifier_name
 - todo

included:
 - Self

excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Carthage
 - Pods